#INTRO
#Set up is quick and easy. Simply replace any example text with your nonprofit's information.
#To leave a field blank, simply remove everything after the colon (:) or place a hashtag (#) at the start of the line.
#If you see '> # Enter on the next line', be sure the next line remains indented two spaces.

#REQUIRED
org_name: <b>JUMPSTARTS</b>
org_summary: > # Enter your summary on the next line. Be sure to indent by two spaces.
  Make your Social Venture:
  <p>
    Sustainable.<br />
    Scalable.<br />
    Investible.<br />
    </p>
org_full_description: > # Enter your description on the next line. Be sure to indent by two spaces.\
  <b>WHAT?</b>
  <p>JumpStarts are <u>monthly problem-solving sessions</u> that employ guided group discussion (3hrs) to unpack and to solve a highly-focused <u>strategic/operational business challenge</u> — a challenge that must be practically resolved before the Featured Startup can progress to its next stage of sustainable growth.</p>
  <p><u>JUMPSTART SESSIONS</u></p>
    <p>JumpStarts bring together:</p>
    <p>
    Founders of 1 Featured Social Startup (non-profit, for-profit, benefit corp., hybrid)<br />
    7 Expert Panelists<br />
    1 Goldilox Problem<br />
    </p>
  <p><u>GOLDILOX PROBLEM</u></p>
    <p>Goldilox Problem = a focused Business/Change Model problem, neither too broad nor too narrow for a three-hour collaborative discussion.</p>
    <p>
    GP Question Frames:<br />
    A Challenge to Overcome or An Opportunity to Seize: How do we solve or accomplish ___________?”<br />
    Choosing Between Alternatives: Should we pursue either Option A or Option B?<br />
    </p>
  
  VALUE
  VALUE FOR FOUNDERS
  JumpStarts help the founders of promising Social Startups diagnose and address what is broken, missing, or under-developed in their Business/Change Models.
  The end-goal of the JumpStart session is to produce 3 Actionable Solutions for the Featured Social Startup. An 'Actionable Solution' describes a recipe-for-action: a sequence of discrete, executable steps.
  
  VALUE FOR EXPERTS
  JumpStarts bring together individual experts with their like-minded colleagues in order to collaboratively solve practical problems for social startups.
  But the greater payoff is the contribution made to a larger shared understanding within a growing network of Experts and Founders of how to build social startups that are uncommonly effective engines of change.
  
  PROCESS
  Throughout the JumpStart Process the emphasis is always upon the practical, real-world verification of all strategic/operational prescriptions and hypotheses.
  The goal is to not merely help individual social startups become more successful — the larger project is to develop an evolving Knowledge Base about how to best design and structure a 21st-Century Social Venture.

  37hrs of Pre-Event Prep
  Key to the effectiveness of the JumpStart experience is the 37hrs of Prep Time that take place before the actual JumpStart.
  Across seven two-hour sessions (plus between-session homework), the Featured Startup’s Business/Change Model is systematically dissected, analyzed, and diagnosed.
  This rigorous analysis in turn produces a high-value Goldilox Problem: which seven Experts will then focus upon in order to produce three Actionable Solutions.
  
  Six-Months of Ongoing Support
  Post-JumpStart, the Featured Startup receives twice-monthly Support Sessions (2 one-hour sessions) to ensure continued progress in implementing and adapting the Expert Panel’s 3 Actionable Solutions.
  
  Outcomes Reporting Event
  Six-months later, the Featured Startup returns to the Expert Panel in order to report on Solutions Outcomes + Lessons Learned.
  The Featured Startup receives an additional 10hrs of prep support prior to the Outcomes Reporting Event.
  
  Case Study
  The entire six-month arc is captured and published in a Case Study that describes:
  <p>
    What Worked?<br />
    What Didn't?<br />
    What Was Learned?<br />
    Recommendations for Future Applications.<br />
    </p>
 
  PARTICIPATE
  Qualified Founders + Experts are invited to apply.
  We have a rapidly growing waiting list of both Featured Startups and Expert Panelists — so please don't delay :)
  
  FOUNDERS
  What's Stopping You?
  Featured Startups must apply: because we ask great questions that will make you objectively assess your venture, the application process itself is  a highly valuable experience for founders.
  5 Preliminary Questions:
  We start by asking you the following to see if we''re on the same page.
  If so, we schedule a face-to-face where we explain the complete process in full detail. Click below to get the process started.
  (1a) What is The Problem?  (in 1 sentence only)
  (1b) What is Your Solution?  (in 1 sentence only)
  (2) Who is your Early Adopter — and how many of them are paying you now?
  (3) How fast are you currently growing — measured how?
  (4) How does your venture reconcile Purpose and Profit?
  (5) What’s keeping you up at night — what’s stopping you?
  Get the Ball Rolling ---> Email
  We'll be in touch within 24hrs.
  
  EXPERT PANELISTS
  What's Your Competency?
  Every JumpStart brings together a panel of 7 Experts.
  Because every social startup is unique, every JumpStart requires a distinct combination of expertise and experience. We curate each panel from the competencies below — which are yours?
  Marketing (Inbound Marketing, Social Marketing, Content Marketing).<br />
  Content (Content Development, Content Management, Content Marketing).<br />
  Storytelling (Text, Video, Journalism).<br />
  Community Building (Membership, Volunteers, Advocacy).<br />
  CSR (Corporate Volunteer Programs, In-Kind Programs, Corporate Foundations).<br />
  Volunteer Experience (Corporate, Institutional, Online Volunteer Platforms).<br />
  Advocacy (Lobbyists, Political Strategists, Coalistion Builders).<br />
  Funders (Impact Investors, Foundations, Philanthropic Advisors, Gov.).<br />
  Data (Data Analytics, Data Visualization, Performance/Impact Measurement).<br />
  Design (UI/UX, Product Design, Graphic Design, Human Factors).<br />
  Programming (Software Developer, Database Developer).<br />
  Legal (IP, Incorporation Strategies).<br />
  Financial (CFO, CPA, Tax Strategies).<br />
  Operations (COO, Program Managers, Systems Designers, IT/IS).<br />
  Sales (Sales Operations, Customer Service, Customer Experience).<br />
  HR (Talent Acquisition/Development, Start-Up Staff Scaling/Structure).<br />
  Get on a Panel ---> Email
  We'll be in touch within 24hrs.
  
 
#OPTIONAL
#Non US-address support coming soon
org_general_email_inbox: info@socialrocketfactory.com
org_street_address: #1355 Market Street #Please include suite number on the line below
org_address_suite: #Suite 900
org_city: New York
org_state: NY
org_zip: > # Enter zip on next line. Be sure to indent by two spaces.
  
org_phone: 
  

#SOCIAL MEDIA
org_twitter_username: #
org_facebook_username: #
org_instagram_username:

#TAX STATUS
#Your site will display an appropriate message below the Donate section
#If your organization is fiscally sponsored, enter true below and add your sponsor's name. Otherwise enter false.
fiscal_sponsor: false
fiscal_sponsor_name:
#If your organization is currently registered as a 501(c)3 organization, enter true below. Otherwise enter false. Enter false if you have a fiscal sponsor.
501c3: false

#ONLINE DONATIONS & EMAIL SIGNUPS
#To use these services, enter the required usernames. For further instructions, consult the README file.
#If you do not wish to use a service, simply remove everything after the colon (:), leaving the item blank
donorbox_campaign_name: 
tinyletter_username: socialrocketfactory

#SEARCH ENGINES
#Changing this next setting to 'true' will allow your site to be indexed by search engines (like Google)
publish: false

#THEME
#Select one of the five color schemes (default, one, two, three, or four)
site_theme: "one"

# *** DO NOT CHANGE ANYTHING BELOW THIS LINE ***

# Unless you know what you're doing, no need to change anything below
# Build settings
baseurl: "" # the subpath of your site, e.g. /blog/
markdown: kramdown
kramdown:
  input: GFM

sass:
    sass_dir: assets/_sass
    style: compressed

#Features under development
#These are not yet fully supported, but should give you a head start if you know what you're doing
paypal_button_id: #Not yet available
smartergiving_id: #Not yet available
#mailchimp_embed_code: > # Enter Mailchimp post url on next line.
#  //getkyn.us5.list-manage.com/subscribe/post?u=1407d7ee4cd0d47986cd54315&amp;id=cdc32b64fe
#mailchimp_spam_guard: b_753395b9f963c9ea2d6980b7c_9e1559c2f0


gems:
  - jekyll-admin